---
# Set the environment variable for OpenSearch initial admin password
- name: Set environment variable for OpenSearch initial admin password
  shell: "export OPENSEARCH_INITIAL_ADMIN_PASSWORD='{{ opensearch_admin_password }}'"
  become: yes

# Install OpenSearch
- name: Install OpenSearch
  apt:
    name: opensearch
    state: present
  environment:
    OPENSEARCH_INITIAL_ADMIN_PASSWORD: "{{ opensearch_admin_password }}"
  become: yes

# Configure OpenSearch to listen on the appropriate port
- name: Configure OpenSearch to listen on the appropriate port
  template:
    src: opensearch.yml.j2
    dest: /etc/opensearch/opensearch.yml
    mode: '0644'
  become: yes

# Restart OpenSearch service
- name: Restart OpenSearch service
  service:
    name: opensearch
    state: restarted
  become: yes

